os:
  - linux
before_install:
  - sudo wget http://master.dl.sourceforge.net/project/d-apt/files/d-apt.list -O /etc/apt/sources.list.d/d-apt.list
  - wget -qO - https://dlang.org/d-keyring.gpg | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install -qq --force-yes dmd-bin dub dcd dfix dfmt dscanner libphobos2-dev libevent-dev
script:
  - dub build
  - dub test
  - dscanner --styleCheck source 2>&1 || echo "Style check!"
  - dscanner --syntaxCheck source 2>&1 || echo "Syntax check!"
  - dub build --build=ddox
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs
  github_token: $GITHUB_TOKEN
  on:
    branch: master
